# -*- coding: utf-8 -*-
"""24-9-2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cVyIxwE2Bkjh0Jy9dB2bFySIH3Izw-wv

**Task 1**
"""

import matplotlib.pyplot as plt

months = [ "JAN" , "FEB" , "MAR" , "APR" , "MAY" , "JUN"]

google_search = [1200 , 1400 , 1600 , 1800 , 2000 , 2200 ]

social_media = [900 , 1100 , 1300 , 1500 , 1700 , 1900 ]

direct_vistors = [1000 , 2000 , 3000 , 4000 , 5000 , 6000 ]

plt.figure(figsize=(10 , 5))

plt.stackplot(
    months,
    google_search,
    social_media,
    direct_vistors,

  labels=[
    "Google_search",
    "Social_media",
    "Direct_vistors"
  ],
  colors=[
    "skyblue",
    "orange",
    "lightgreen"
  ]
)

plt.title("Website Visitors by Traffic Source")

plt.xlabel("Month")

plt.ylabel("Visitors")

plt.legend()

plt.show()

"""**Task 2**"""

months = ["JUL",  "AUG" , "SEPT" , "OCT" , "NOV" , "DEC"]

electronics = [100  , 150 , 200 , 250 , 300 , 350]

clothing = [150 , 200 , 250 , 300 , 350 , 400]

grocery = [200 , 250 , 300 , 350 , 400 , 450]

plt.figure(figsize=(10 , 5))

plt.stackplot(
    months,
    electronics,
    clothing,
    grocery,

  labels=[
      "Electronics",
      "Clothing",
      "Grocery",
  ],
  colors=[
   "orange",
   "lightblue",
   "green"
  ]
)

plt.title("Monthly Product Sales")

plt.xlabel("Month")

plt.ylabel("Sales")

plt.legend()

plt.show()

"""**Task 3**"""

days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

coding = [5, 6, 4, 5, 6, 3, 1]
meetings = [2, 1, 2, 1, 2, 1, 1]
training = [1, 1, 2, 2, 1, 2, 1]

plt.stackplot(days, coding, meetings, training,
              labels=["Coding", "Meetings", "Training"])

plt.title("Employee Work Hours Analysis")
plt.xlabel("Days of the Week")
plt.ylabel("Hours")
plt.legend()
plt.show()

"""**Task 4**"""

months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]

videos = [10, 12, 14, 13, 16, 18]
games = [8, 9, 10, 11, 12, 13]
chat = [6, 7, 8, 9, 10, 11]
shopping = [4, 5, 6, 5, 7, 8]

plt.stackplot(months, videos, games, chat, shopping,
              labels=["Videos", "Games", "Chat", "Shopping"])

plt.title("Mobile App Usage Analysis")
plt.xlabel("Months")
plt.ylabel("Usage Hours")
plt.legend()
plt.show()

"""**Task 5**"""

days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

python = [2, 3, 2, 3, 2, 4, 3]
sql = [1, 2, 1, 2, 2, 2, 1]
mathematics = [2, 1, 2, 1, 2, 2, 2]
revision = [1, 1, 2, 1, 1, 2, 2]

plt.stackplot(days, python, sql, mathematics, revision,
              labels=["Python", "SQL", "Mathematics", "Revision"])

plt.title("Student Study Analysis")
plt.xlabel("Days")
plt.ylabel("Hours")
plt.legend()
plt.show()

"""**Task 6**"""

months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]

electronics = [120, 150, 140, 170, 180, 200]
fashion = [100, 130, 125, 150, 160, 175]
grocery = [180, 190, 200, 210, 220, 230]

plt.stackplot(months, electronics, fashion, grocery,
              labels=["Electronics", "Fashion", "Grocery"])

plt.title("E-Commerce Orders Analysis")
plt.xlabel("Months")
plt.ylabel("Number of Orders")
plt.legend()
plt.show()

"""**Task 7**"""

months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]

tutorials = [5000, 6000, 7000, 8000, 9000, 10000]
shorts = [8000, 9000, 11000, 12000, 14000, 16000]
reviews = [3000, 4000, 4500, 5000, 6000, 7000]

plt.stackplot(months, tutorials, shorts, reviews,
              labels=["Tutorials", "Shorts", "Reviews"])

plt.title("YouTube Channel Performance")
plt.xlabel("Months")
plt.ylabel("Views")
plt.legend()
plt.show()

"""**Task 8**"""

days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

breakfast = [2000, 2200, 2100, 2300, 2500, 3000, 3200]
lunch = [4000, 4200, 4100, 4500, 4800, 5500, 5800]
dinner = [5000, 5200, 5100, 5500, 6000, 7000, 7500]

plt.stackplot(days, breakfast, lunch, dinner,
              labels=["Breakfast", "Lunch", "Dinner"])

plt.title("Restaurant Sales Analysis")
plt.xlabel("Days")
plt.ylabel("Sales Amount")
plt.legend()
plt.show()

"""**Task 9**"""

days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

walking = [30, 35, 40, 30, 45, 50, 60]
running = [20, 25, 30, 25, 35, 40, 45]
cycling = [15, 20, 25, 20, 30, 35, 40]

plt.stackplot(days, walking, running, cycling,
              labels=["Walking", "Running", "Cycling"])

plt.title("Fitness Activity Analysis")
plt.xlabel("Days")
plt.ylabel("Minutes")
plt.legend()
plt.show()

"""**Task 10**"""

months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]

ac = [20, 25, 30, 45, 70, 90]
refrigerator = [30, 32, 31, 33, 35, 36]
lights = [15, 16, 14, 17, 18, 20]
other_appliances = [25, 28, 30, 32, 35, 40]

plt.stackplot(months, ac, refrigerator, lights, other_appliances,
              labels=["AC", "Refrigerator", "Lights", "Other Appliances"])

plt.title("Electricity Consumption Analysis")
plt.xlabel("Months")
plt.ylabel("Electricity Units")
plt.legend()
plt.show()