# -*- coding: utf-8 -*-
"""30-9-2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AcaAs8q1Ria7q6wg9leUJfP7_xmJETY4

# **Intro to Seaborn**

**Import Seaborn**
"""

import seaborn as sns
import matplotlib.pyplot as plt

"""**Load seaborn's built-in dataset tips or iris.**"""

tips = sns.load_dataset("tips")

print(tips.head())
print(tips.info())

"""# **Distribution Plots**

**Histogram**
"""

tips = sns.load_dataset("tips")

sns.histplot(data=tips,x="total_bill")

plt.title("Histogram of Total Bill")

plt.show()

"""**KDE Plot**"""

tips = sns.load_dataset("tips")

sns.kdeplot(data=tips,x="total_bill")

plt.title("KDE plot of total bill")

plt.show()

"""**Histogram + KDE using**"""

tips = sns.load_dataset("tips")

sns.displot(data=tips,x="total_bill",kde=True)

plt.title("Histogram with KDE")

plt.show()

"""# **Categorical plots**

**Box plot**
"""

tips = sns.load_dataset("tips")

sns.boxplot(data=tips,x="day",y="total_bill")

plt.title("Total bill by day")

plt.show()

"""**Violinplot**"""

tips = sns.load_dataset("tips")

sns.violinplot(data=tips,x="sex",y="tip")

plt.title("Tip Amount by Gender")
plt.show()

"""**Stripplot: Tips by Smoker Status**"""

tips = sns.load_dataset("tips")

sns.stripplot(data=tips,x="smoker",y="tip")

plt.title("Tip Amount by smoker Status")

plt.show()

"""# **Relation Plots**

**Scatterplot**
"""

tips = sns.load_dataset("tips")

sns.scatterplot(data=tips, x="total_bill", y="tip")

plt.title("Total Bill VS Tip")

"""**Hue,size and style**"""

tips = sns.load_dataset("tips")

sns.scatterplot(
    data=tips,
    x="total_bill",
    y="tip",
    hue="smoker",
    size="size",
    style="sex"
)

plt.title("Total Bill vs Tip")

plt.show()

"""**Line plot**"""

tips = sns.load_dataset("tips")

sns.lineplot(data=tips, x="day", y="tip")

plt.title("Trend of Tips by Day")
plt.xlabel("Day")
plt.ylabel("Tip")
plt.show()

"""# **MATRIX PLOTS**

**Heatmap**
"""

numeric_data = tips.select_dtypes(include="number")

correlation = numeric_data.corr()

sns.heatmap(
    correlation,
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")
plt.show()

"""**annotations + color map**"""

tips = sns.load_dataset("tips")

numeric_data = tips.select_dtypes(include="number")
correlation = numeric_data.corr()

sns.heatmap(
    correlation,
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")
plt.show()

"""**Clustermap**"""

sns.clustermap(
    correlation,
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Clustermap")
plt.show()

"""# **Regression Plots**

**Regplot**
"""

tips = sns.load_dataset("tips")

sns.regplot(
    data=tips,
    x="total_bill",
    y="tip"
)

plt.title("Linear Relationship: Total Bill vs Tip")
plt.xlabel("Total Bill")
plt.ylabel("Tip")
plt.show()

"""**Lmplot**"""

tips = sns.load_dataset("tips")

sns.lmplot(
    data=tips,
    x="total_bill",
    y="tip",
    hue="smoker"
)

plt.title("Regression by Smoker Status")
#plt.legend()
plt.show()

"""# **Styling and Themes**

**"darkgrid", "whitegrid"**
"""

tips = sns.load_dataset("tips")

sns.set_theme(style="darkgrid")

sns.scatterplot(data=tips, x="total_bill", y="tip")

plt.title("Darkgrid Theme")
plt.show()

"""**Customize color palette — pastel**"""

tips = sns.load_dataset("tips")

sns.set_theme(style="whitegrid")

sns.boxplot(
    data=tips,
    x="day",
    y="total_bill",
    hue="day",
    palette="pastel",
    legend=True
)

plt.title("Pastel Color Palette")
plt.show()

"""**Publication-style context**"""

tips = sns.load_dataset("tips")

sns.set_context("paper")

sns.scatterplot(data=tips, x="total_bill", y="tip")

plt.title("Publication Style Plot")
plt.show()

